version: "3.9"

networks:
  default:
    external: true
    name: dev

services:
  app:
    build: .
    container_name: app
    env_file:
      - "src/main/resources/docker.env"
    ports:
      - "8080:8080"
      - "8090:8090"
    restart: always
    depends_on:
      - httpbin
  httpbin:
    image: kennethreitz/httpbin
    container_name: httpbin
    ports:
      - "8001:80"
    restart: always
